Some more spec document cleanup
eclipse-ee4j/servlet-api pull request #364
Opened 2020-09-19 00:22 UTC by stuartwdouglas

Fixes #363

This should address most of comments in the issue, bar a few things:

> In Chapt. 14, Deployment Descriptors the text still says "All legacy deployment descriptors must be supported." I am not sure if that will be possible. Please review and update the text if needed.

Not sure what to do about this one. The XML does not directly reference package names so really there is no reason why we can't support old versions, but old apps will be using the old namespace which clearly won't work without some form of transformation. Maybe we should just drop this requirement from the spec altogether, and leave it up to the implementations as to what they support (however add it back in 5.1, so 5.1 needs to support 5.0 descriptors).

> References to external specifications probably need to specify a minimum version due to the name-space changes (e.g. Authorization 2.0 or higher)

I was not really sure what to do about this, maybe it needs a new section on compatible spec versions?

2020-09-22 14:55 UTC, markt-asf commented
I'm leaning towards keeping the requirement to support legacy descriptors. (Automated) migration of applications is simpler if the descriptors can be left as-is and the more we can do to ease the migration path, the more likely it is the users will migrate sooner and the associated costs of retaining this requirement appear to be negligible.

Rather than add versions to every spec reference, what about a general statement along the lines of

> References to other specifications that are part of the Jakarta EE platform exclude the versions of those specifications that target Jakarta EE 8 due to the different name-space used.

2020-09-22 23:38 UTC, stuartwdouglas commented
I have updated the section on the spec versions. +1 to leaving the compatibility requirements as is.

2020-09-24 05:20 UTC, hussainnm requested changes
JAX-WS is Jakarta XML Web Services and not Jakarta Enterprise Web Services

2020-10-13 22:04 UTC, stuartwdouglas commented
I have updated this and rebased my 5.1 PR. IMHO we should get this in, then merge the 5.1 PR and branch 5.0.

2020-10-13 23:13 UTC, arjantijms commented
> I have updated this and rebased my 5.1 PR. IMHO we should get this in, then merge the 5.1 PR and branch 5.0.

Indeed, now would be the time for that. I'll branch 5.0, and do the 5.1 PR merge then.

2020-10-13 23:17 UTC, arjantijms approved these changes

2020-10-13 23:17 UTC, merged