Add a module-info.java
eclipse-ee4j/servlet-api pull request #442
Opened 2021-11-16 22:58 UTC by arjantijms

Module name is `jakarta.servlet` (Per the naming [conventions](https://github.com/jakartaee/specification-committee/blob/master/names.adoc))
Exports the 4 API packages

Opens the 4 API packages as well to prevent errors like:

```
[ERROR] jakarta.servlet.http.CookieTest.testValue  Time elapsed: 0 s  <<< ERROR!

java.lang.reflect.InaccessibleObjectException: 
    Unable to make jakarta.servlet.http.CookieTest() accessible: 
        module jakarta.servlet does not "opens jakarta.servlet.http" to unnamed module @ffaa6af
```

Signed-off-by: arjantijms <arjan.tijms@gmail.com>

2021-11-17 11:27 UTC, markt-asf commented
I'm not sure opening those packages by default is what we want to do. Changing the Surefire Plugin to:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0-M5</version>
    <configuration>
        <argLine>--add-opens=jakarta.servlet/jakarta.servlet.http=ALL-UNNAMED</argLine>
    </configuration>
</plugin>
```
is perhaps a better approach.

I'm also not sure about `jakarta.servlet.resources`. I'm currently testing this locally to see what - if anything - is required for the schema to be accessible from the API JAR in a JPMS environment.

2021-11-17 11:33 UTC, stuartwdouglas requested changes
Can we just make CookieTest and all its methods public instead?

2021-11-17 11:37 UTC, markt-asf commented
> Can we just make CookieTest and all its methods public instead?

2021-11-17 11:42 UTC, stuartwdouglas commented
The issue here though is that the test is private, and part of the same package, so JUnit can't load the test. Just make the test public.

2021-11-17 11:46 UTC, markt-asf commented
Confirmed. Making the test class and each test method public is sufficient to resolve the error. That solution works for me. (still need to fix resources)

2021-11-17 11:50 UTC, stuartwdouglas requested changes
This will also need an entry in the changelog.

2021-11-17 20:06 UTC, arjantijms commented
There's seemingly a debate surrounding how to go about adding tests to the same Maven module in a modular Java world. The short of it, it's not entirely trivial, and there's a mismatch between Maven and Java modules. Maven distinguishes between regular and test dependencies, while Java modules does not.

Luckily the tests here are simple enough and don't have dependencies of their own.

2021-11-17 20:39 UTC, arjantijms commented
@stuartwdouglas @markt-asf See updated PR

2021-11-18 10:26 UTC, markt-asf approved these changes
LGTM

2021-11-18 10:29 UTC, stuartwdouglas approved these changes

2021-11-18 22:23 UTC, merged